# Use an official Python runtime as a parent image
FROM python:3.9.1

# Set environment variables for Django
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SECRET_KEY c6e79e7784e9081308e2e0d8b502a5d924de2a901e8fd4c5
ENV POSTGRES_DB niabraze_quotes
ENV POSTGRES_USER niabraze
ENV POSTGRES_PASSWORD y7Kv5Gqo4izhLB

# Create and set the working directory
RUN mkdir /app
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the Django app into the container
COPY . /app

# Collect static files
RUN python manage.py collectstatic --noinput


# Start Gunicorn
# RUN python manage.py createsuperuser --username abluemleiv --email abluemleiv@gmail.com --no-input
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "niabraze.wsgi"]
