# Generated by Django 4.2.4 on 2023-08-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.TextField(blank=True, null=True)),
                ('contact_name', models.TextField()),
                ('brazed', models.BooleanField(default=False)),
            ],
        ),
    ]
