# Generated by Django 4.2.4 on 2023-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_particle'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='grit',
            field=models.CharField(blank=True, choices=[('16/18', '16/18'), ('18/20', '18/20'), ('20/30', '20/30'), ('30/40', '30/40'), ('40/50', '40/50'), ('50/60', '50/60'), ('60/80', '60/80'), ('80/100', '80/100'), ('80/120', '80/120'), ('100/120', '100/120'), ('120/140', '120/140'), ('140/170', '140/170'), ('170/200', '170/200'), ('200/230', '200/230'), ('230/270', '230/270'), ('270/325', '270/325'), ('325/400', '325/400'), ('400', '400'), ('500', '500'), ('600', '600'), ('800', '800'), ('1200', '1200'), ('1500', '1500'), ('2000', '2000')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='particle',
            field=models.CharField(choices=[('synthetic', 'Synthetic'), ('natural', 'Natural'), ('blend', 'Blend'), ('cbn', 'CBN')], default='synthetic', max_length=20),
        ),
    ]
