# Generated by Django 4.2.4 on 2023-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_grit_alter_quote_particle'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fixture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='fixture_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tooling_type',
            field=models.CharField(choices=[('customerProvided', 'Customer Provided'), ('stripReplate', 'Strip & Replate'), ('blankNeeded', 'Blank Needed')], default='customerProvided', max_length=20),
        ),
    ]
