# Generated by Django 4.2.4 on 2023-09-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_fixture_quote_fixture_cost_quote_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tooling_type',
        ),
        migrations.AddField(
            model_name='quote',
            name='blank_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='cleaning_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moreDifficult', 'More Difficult'), ('veryDifficult', 'Very Difficult')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='expedited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='machine_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='machining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='pack_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='plating_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='prep_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='strip_replate',
            field=models.CharField(blank=True, choices=[('small/easy part', 'Small/Easy Part'), ('medium size/difficulty', 'Medium Size/Difficulty'), ('large/difficult part', 'Large/Difficult Part')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='fixture_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
