# Generated by Django 4.2.4 on 2023-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_quote_tooling_type_quote_blank_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moreDifficult', 'More Difficult'), ('veryDifficult', 'Very Difficult')], max_length=20),
        ),
    ]
