# Generated by Django 4.2.4 on 2023-09-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_quote_surface_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tooling_type',
            field=models.CharField(choices=[('Customer Provided', 'Customer Provided'), ('Strip & Replate', 'Strip & Replate'), ('Blank Needed', 'Blank Needed')], default='Customer Provided', max_length=20),
            preserve_default=False,
        ),
    ]
