# Generated by Django 4.2.4 on 2023-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quote_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='cleaning_labor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pack_labor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='plating_labor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='prep_labor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='surface_area',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
